---
homekit:
  name: Home Assistant
  filter:
    include_entities:
      - light.gerald
      - light.stoof
      - light.bertie
      - light.landing
      - light.front
      - light.back
      - light.fairy
      - climate.living_room
      - climate.bedroom
      - climate.landing
      - climate.spare_room
      - climate.bathroom
      - input_boolean.cinema_state
