---
- alias: Away Mode
  trigger:
    platform: state
    entity_id: group.family
    to: not_home
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.home_state
