---
- alias: In Bed Notify

  trigger:
    - platform: event
      event_type: state_changed
      event_data:
        entity_id: binary_sensor.in_bed_sensor

  condition:
    - condition: template
      value_template: '{{ trigger.event.data.new_state.state != trigger.event.data.old_state.state }}'

  action:
    - service: notify.bertie_iphone
      data:
        message: In bed sensor set to '{{ trigger.event.data.new_state.state }}'
