---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: master
    hooks:
      - id: shfmt
      - id: shellcheck

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.0.11
    hooks:
      - id: yamlfmt
