---
repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.4
    hooks:
      - id: shfmt
        name: Format shell scripts
      - id: shellcheck
        name: Lint shell scripts

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.2.1
    hooks:
      - id: prettier
        name: Run Prettier

  - repo: local
    hooks:
      - id: home-assistant-config-check
        name: Validate config
        entry: scripts/config-check.sh
        language: script
        pass_filenames: false
