---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "master"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"
      - id: "check-added-large-files"

  - repo: "https://github.com/jumanjihouse/pre-commit-hooks"
    rev: "master"
    hooks:
      - id: "shfmt"
      - id: "shellcheck"

  - repo: "https://github.com/adrienverge/yamllint.git"
    rev: "master"
    hooks:
      - id: "yamllint"
        name: "Lint YAML"
        args: ["--format", "parsable", "--strict"]

  - repo: "local"
    hooks:
      - id: "home-assistant-config-check"
        name: "Check Home Assistant config"
        entry: "scripts/config-check.sh"
        language: "script"
        pass_filenames: false
