---
repos:
  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "master"
    hooks:
      - id: "trailing-whitespace"
      - id: "end-of-file-fixer"

  - repo: "https://github.com/jumanjihouse/pre-commit-hooks"
    rev: "master"
    hooks:
      - id: "shfmt"
      - id: "shellcheck"

  - repo: https://github.com/prettier/prettier
    rev: master
    hooks:
      - id: prettier

  # - repo: "local"
  #   hooks:
  #     - id: "home-assistant-config-check"
  #       name: "Check Home Assistant config"
  #       entry: "scripts/config-check.sh"
  #       language: "script"
  #       pass_filenames: false
