language: python
cache: pip
python:
  - "3.5"
install:
  - "pip3 install homeassistant"
script:
  - "mv travis/mock_secrets.yaml secrets.yaml"
  - "sudo mkdir /ssl"
  - "sudo touch /ssl/fullchain.pem"
  - "sudo touch /ssl/privkey.pem"
  - "hass -c . --script check_config | tee check.output"
  - '! less check.output | grep -q "Failed config"'
