- id: travis_build_failed
  alias: System Travis Build Failed
  trigger:
    - platform: state
      entity_id: sensor.covertbert_home_assistant_last_build_state
      from: "started"
      to: "failed"
  action:
    - service: notify.ios_robert_g_hs_iphone
      data_template:
        message: >
          Travis build failed! {{ "\uD83E\uDD2C" }}
        data:
          url: https://travis-ci.com/covertbert/home-assistant

- id: travis_build_passed
  alias: System Travis Build Passed
  trigger:
    - platform: state
      entity_id: sensor.travis_build_status
      from: "started"
      to: "passed"
  action:
    - service: notify.ios_robert_g_hs_iphone
      data_template:
        message: >
          Travis build passed! {{ "\uD83D\uDC4D" }}
        data:
          url: https://travis-ci.com/covertbert/home-assistant
    # - service: hassio.addon_start
    #   data:
    #     addon: core_git_pull
