homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 200
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize

default_config:

frontend:
  themes: !include_dir_merge_named themes

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password

tts:
  - platform: google

discovery:

device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 45

homekit:
  filter:
    include_entities:
      - light.living_room_front
      - climate.heating

hive:
  username: !secret hive_username
  password: !secret hive_password

sensor: !include_dir_merge_list sensors
zone: !include_dir_merge_list zones
group: !include_dir_merge_named groups
light: !include_dir_merge_named lights
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
