homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 200
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize

default_config:

frontend:
  themes: !include_dir_merge_named themes

sensor:
  - platform: travisci
    api_key: !secret github_access_token
    monitored_conditions:
      - last_build_state
  - platform: darksky
    api_key: !secret dark_sky_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

homekit:
  filter:
    include_entities:
      - light.living_room_front
      - climate.heating

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password

discovery:

device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 45

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 50
    icon: mdi:home

  - name: Sainsbury's Office
    latitude: 53.483704
    longitude: -2.241619
    radius: 150
    icon: mdi:home-modern

  - name: Havas Lynx
    latitude: 53.476708
    longitude: -2.239287
    radius: 60
    icon: mdi:home-modern

  - name: Chinley Station
    latitude: 53.340829
    longitude: -1.943956
    radius: 130
    icon: mdi:train

hive:
  username: !secret hive_username
  password: !secret hive_password

tts:
  - platform: google

group: !include_dir_merge_named groups
light: !include_dir_merge_named lights
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
