homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 200
  unit_system: metric
  time_zone: Europe/London
  customize: !include_dir_merge_named customize

default_config:

frontend:
  themes: !include_dir_merge_named themes

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

http:
  base_url: !secret http_base_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

rest_command:
  backup_snapshots:
    url: "http://localhost:8055/gb/doBackup"
    timeout: "240000"

tts:
  - platform: google_translate

discovery:

device_tracker:
  - platform: bluetooth_tracker

google_assistant:
  project_id: !secret ga_id
  api_key: !secret ga_api_key
  exposed_domains:

life360:
  accounts:
    username: !secret life360_username
    password: !secret life360_password  
  show_as_state: [driving, moving]

homekit:
  filter:
    include_entities:
      - light.bedroom_gerald
      - climate.heating

telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - 474430844

notify:
  - name: telegram
    platform: telegram
    chat_id: 474430844

panel_iframe: !include panels/panel_iframe.yaml
sensor: !include_dir_merge_list sensors
zone: !include_dir_merge_list zones
group: !include_dir_merge_named groups
light: !include_dir_merge_list lights
automation: !include_dir_merge_list automations
script: !include_dir_merge_named scripts
