homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 53.382059
  longitude: -1.947517
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 200
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/London
  # Customization file
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

frontend:
  themes: !include themes.yaml

# Weather Prediction
sensor:
  - platform: travisci
    api_key: !secret github_access_token
    monitored_conditions:
      - last_build_state
  - platform: darksky
    api_key: !secret dark_sky_api_key
    forecast:
      - 0
    monitored_conditions:
      - summary
      - icon
      - temperature

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key

homekit:
  filter:
    include_entities:
      - light.living_room_front
      - climate.heating

http:
  base_url: https://hassio-hayfield.duckdns.org:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  api_password: !secret api_password

discovery:

device_tracker:
  - platform: tplink
    host: !secret router_ip
    username: !secret router_username
    password: !secret router_password
    new_device_defaults:
      track_new_devices: true
      hide_if_away: false
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 45

zone:
  - name: Home
    latitude: 53.382059
    longitude: -1.947517
    radius: 50
    icon: mdi:home

  - name: Sainsbury's Office
    latitude: 53.483704
    longitude: -2.241619
    radius: 150
    icon: mdi:home-modern

  - name: Havas Lynx
    latitude: 53.476708
    longitude: -2.239287
    radius: 60
    icon: mdi:home-modern

hive:
  username: !secret hive_username
  password: !secret hive_password

tts:
  - platform: google

group: !include groups.yaml
light: !include lights.yaml
automation: !include automations.yaml
script: !include scripts.yaml
