---
homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 200
  unit_system: metric
  time_zone: Europe/London
  packages: !include_dir_named configuration/integrations
