---
title: "Home"
resources:
  - url: "/local/mini-graph-card-bundle.js?v=0.9.4"
    type: "module"
views:
  - title: "Home"
    icon: "mdi:home"
    panel: false
    path: "default_view"
    badges:
      - "person.steph"
      - "person.bertie"
    cards:
      - entities:
          - entity: "group.media"
          - entity: "input_select.home_state"
          - entity: "input_select.day_state"
          - entity: "input_select.sunrise_state"
          - entity: "light.all_lights"
          - entity: "light.bedroom"
          - entity: "light.living_room"
          - entity: "light.landing"
        show_header_toggle: false
        type: "entities"
      - type: "gauge"
        min: 0
        max: 100
        theme: "default"
        entity: "sensor.disk_use_percent"
        name: "Disk Usage"
      - type: "entities"
        entities:
          - entity: "sensor.last_boot"
      - type: "custom:mini-graph-card"
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - "sensor.memory_use_percent"
        show:
          labels: true
        color_thresholds:
          - value: 0
            color: "#00ff00"
          - value: 20
            color: "#ffa500"
          - value: 80
            color: "#ff0000"
      - type: "custom:mini-graph-card"
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - "sensor.processor_use"
        show:
          labels: true
        color_thresholds:
          - value: 0
            color: "#00ff00"
          - value: 20
            color: "#ffa500"
          - value: 80
            color: "#ff0000"
      - type: "custom:mini-graph-card"
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - "sensor.speedtest_download"
        show:
          labels: true
        color_thresholds:
          - value: 0
            color: "#ff0000"
          - value: 40
            color: "#ffa500"
          - value: 50
            color: "#00ff00"
      - type: "custom:mini-graph-card"
        hours_to_show: 24
        points_per_hour: 2
        entities:
          - "sensor.speedtest_upload"
        show:
          labels: true
        color_thresholds:
          - value: 0
            color: "#ff0000"
          - value: 7
            color: "#ffa500"
          - value: 9
            color: "#00ff00"
  - title: "Living Room"
    icon: "mdi:sofa"
    panel: false
    badges: []
    cards:
      - entity: "media_player.living_room_tv"
        type: "media-control"
      - entities:
          - entity: "light.back"
          - entity: "light.front"
        title: "Lights"
        type: "entities"
  - title: "Kitchen"
    icon: "mdi:fridge-outline"
    badges: []
    cards:
      - entity: "media_player.kitchen_speaker"
        type: "media-control"
  - title: "Bedroom"
    icon: "mdi:bed-empty"
    badges: []
    cards:
      - entity: "media_player.bedroom_speaker"
        type: "media-control"
      - entities:
          - entity: "light.stoof"
          - entity: "light.gerald"
          - entity: "light.bertie"
          - entity: "sensor.hue_motion_sensor_1_light_level"
          - entity: "sensor.hue_motion_sensor_1_temperature"
        title: "Lights"
        type: "entities"
  - title: "Landing"
    icon: "mdi:stairs"
    badges: []
    cards:
      - entities:
          - entity: "light.landing"
        title: "Lights"
        type: "entities"
  - title: "Spare Room"
    icon: "mdi:bed-empty"
    cards:
      - entities:
          - entity: "light.landing"
        title: "Lights"
        type: "entities"
