---
- alias: "Climate - Coming Home Boost"
  mode: "single"

  trigger:

  action:
    - service: "tado.set_climate_timer"
      data:
        entity_id: "climate.living_room"
        time_period: "02:00:00"
        temperature: 21
    - service: "tado.set_climate_timer"
      data:
        entity_id: "climate.landing"
        time_period: "03:00:00"
        temperature: 21
