---
type: vertical-stack
cards:
  - title: Landing
    type: glance
    entities:
      - entity: climate.landing
      - entity: sensor.landing_temperature
      - entity: sensor.landing_humidity
    state_color: true
    show_icon: true
    show_name: false

  - type: entities
    entities:
      - entity: light.landing
      - entity: switch.workstation_plug_2
    show_header_toggle: false

  - type: entities
    entities:
      - entity: sensor.landing_button_power
        name: Button Battery

  - type: entities
    entities:
      - entity: binary_sensor.landing_hue_motion
        name: Landing Motion
      - entity: sensor.landing_hue_light_level
        name: Landing Light Level
