---
type: vertical-stack
cards:
  - title: Living Room
    type: glance
    entities:
      - entity: climate.living_room
      - entity: sensor.living_room_temperature
      - entity: sensor.living_room_humidity
      - entity: media_player.living_room_tv
    state_color: true
    show_icon: true
    show_name: false
    columns: 4

  - type: entities
    entities:
      - entity: light.front
      - entity: light.back
      - entity: light.fairy
    show_header_toggle: false

  - type: vertical-stack
    cards:
      - title: Christmas Tree
        type: glance
        entities:
          - entity: sensor.christmas_tree_battery
          - entity: sensor.christmas_tree_temperature
          - entity: sensor.christmas_tree_light_intensity
          - entity: sensor.christmas_tree_moisture
          - entity: sensor.christmas_tree_conductivity
        show_name: false
      - title: Maranta
        type: glance
        entities:
          - entity: sensor.maranta_battery
          - entity: sensor.maranta_temperature
          - entity: sensor.maranta_light_intensity
          - entity: sensor.maranta_moisture
          - entity: sensor.maranta_conductivity
        show_name: false

  - type: entities
    entities:
      - entity: sensor.living_room_cupboard_battery
        name: Cupboard Battery
      - entity: sensor.living_room_cupboard_temperature
        name: Cupboard Temperature
      - entity: sensor.living_room_cupboard_humidity
        name: Cupboard Humidity

  - type: entities
    entities:
      - entity: sensor.living_room_light_sensor_battery
        name: Light Sensor Battery
      - entity: sensor.living_room_light_sensor_light
        name: Light Sensor Lux

  - type: entities
    entities:
      - entity: sensor.living_room_button_power
        name: Button Battery
