---
type: vertical-stack
cards:
  - title: Living Room
    type: glance
    entities:
      - entity: climate.living_room
      - entity: sensor.living_room_temperature
      - entity: sensor.living_room_humidity
      - entity: media_player.living_room_tv
    state_color: true
    show_icon: true
    show_name: false
    columns: 4

  - type: entities
    entities:
      - entity: light.front
      - entity: light.back
      - entity: light.fairy
    show_header_toggle: false

  - type: entities
    entities:
      - entity: sensor.living_room_cupboard_battery
        name: Cupboard Battery
      - entity: sensor.living_room_cupboard_temperature
        name: Cupboard Temperature
      - entity: sensor.living_room_cupboard_humidity
        name: Cupboard Humidity

  - type: entities
    entities:
      - entity: sensor.living_room_light_sensor_battery
        name: Light Sensor Battery
      - entity: sensor.living_room_light_sensor_light
        name: Light Sensor Lux

  - type: entities
    entities:
      - entity: sensor.living_room_motion_sensor_power
        name: Motion Sensor Battery
      - entity: binary_sensor.living_room_motion_sensor
        name: Motion Sensor Motion

  - type: entities
    entities:
      - entity: sensor.living_room_button_power
        name: Button Battery
