---
type: vertical-stack
cards:
  - title: Living Room
    type: glance
    entities:
      - entity: climate.living_room
      - entity: sensor.living_room_temperature
      - entity: sensor.living_room_humidity
      - entity: media_player.living_room_tv
    state_color: true
    show_icon: true
    show_name: false
    columns: 4

  - type: entities
    entities:
      - entity: light.front
      - entity: light.back
      - entity: light.fairy
    show_header_toggle: false

  - type: entities
    entities:
      - entity: sensor.maranta_battery
      - entity: sensor.maranta_temperature
      - entity: sensor.maranta_light_intensity
      - entity: sensor.maranta_moisture
      - entity: sensor.maranta_conductivity

  - type: entities
    entities:
      - entity: sensor.living_room_cupboard_battery
      - entity: sensor.living_room_cupboard_temperature
      - entity: sensor.living_room_cupboard_humidity

  - type: entities
    entities:
      - entity: sensor.living_room_light_sensor_battery
      - entity: sensor.living_room_light_sensor_light
