---
type: vertical-stack
cards:
  - title: Living Room
    type: glance
    entities:
      - entity: climate.living_room
      - entity: sensor.living_room_temperature
      - entity: sensor.living_room_humidity
      - entity: media_player.living_room_tv
    state_color: true
    show_icon: true
    show_name: false
    columns: 4
    style: |
      ha-card {
          background-color: var(--primary-background-color);
          border-radius: 15px;
          margin: 10px;
          box-shadow:
            {% if is_state('sun.sun', 'above_horizon') %}
              -4px -4px 8px rgba(255, 255, 255, .5), 5px 5px 8px rgba(0, 0, 0, .03);
            {% elif is_state('sun.sun', 'below_horizon') %}
              -5px -5px 8px rgba(50, 50, 50, .2), 5px 5px 8px rgba(0, 0, 0, .08);
            {% endif %}
      }

  - type: entities
    entities:
      - entity: light.front
      - entity: light.back
      - entity: light.fairy
    show_header_toggle: false

  - type: entities
    entities:
      - entity: sensor.living_room_cupboard_battery
        name: Cupboard Battery
      - entity: sensor.living_room_cupboard_temperature
        name: Cupboard Temperature
      - entity: sensor.living_room_cupboard_humidity
        name: Cupboard Humidity

  - type: entities
    entities:
      - entity: sensor.living_room_light_sensor_battery
        name: Light Sensor Battery
      - entity: sensor.living_room_light_sensor_light
        name: Light Sensor Lux

  - type: entities
    entities:
      - entity: sensor.living_room_button_power
        name: Button Battery
