- alias: Lights - Landing - Schedule
  id: automation_areas_landing_lights_landing_schedule
  mode: single

  triggers:
    # Is the sun about to set
    - trigger: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 5

    # Is the time 9pm
    - trigger: time
      at: "21:00:00"

    # Is the time 0630
    - trigger: time
      at: "06:50:00"

    # Has the sun reached its peak (solar noon)
    - trigger: state
      entity_id: sun.sun
      attribute: rising
      from: true
      to: false

  condition:
    # Someone is home
    - condition: state
      entity_id: input_boolean.home_state
      state: "on"

  action:
    - choose:
        - conditions:
            - condition: time
              after: "21:00:00"
              before: "06:00:00"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.hare

        # Sun has passed its peak — turn off until afternoon
        - conditions:
            - condition: state
              entity_id: sun.sun
              attribute: rising
              state: false
            - condition: time
              after: "10:00:00"
              before: "14:30:00"
          sequence:
            - action: light.turn_off
              target:
                entity_id:
                  - light.hare

        - conditions:
            - condition: time
              after: "14:30:00"
              before: "21:00:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hare
              data:
                color_temp_kelvin: 2600
                brightness_pct: 70

        # Morning — turn on at 7am until solar noon
        - conditions:
            - condition: time
              after: "06:00:00"
              before: "14:30:00"
          sequence:
            - action: light.turn_on
              target:
                entity_id: light.hare
              data:
                color_temp_kelvin: 2600
                brightness_pct: 70
