---
- alias: Climate - Bedroom - Afternoon
  mode: single

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Afernoon

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom
        temperature: 16
