---
- alias: Climate - Bedroom
  mode: queued

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning
    - platform: state
      entity_id: input_select.day_state
      to: Afternoon
    - platform: state
      entity_id: input_select.home_state
      to: Away

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.day_state
              state: Morning
            - condition: state
              entity_id: input_select.home_state
              state: Home
          sequence:
            - service: tado.set_climate_timer
              data:
                entity_id: climate.bedroom
                time_period: 02:00:00
                temperature: 17

      default:
        - service: climate.turn_off
          data:
            entity_id: climate.bedroom
