---
- alias: Climate - Bedroom - Evening

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Evening
    - platform: state
      entity_id: input_boolean.home_state
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.day_state
      state: Evening
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom
        temperature: 17
