---
- alias: Climate - Bedroom - Off

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Evening
    - platform: state
      entity_id: input_select.home_state
      to: Away

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom
        temperature: 12
