---
- alias: Climate - Bedroom - Afternoon

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Afernoon

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.bedroom
        temperature: 21
