---
- alias: Lights - Bedroom

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away
    - platform: state
      entity_id: light.bedroom
      to: 'on'

  condition:
    - condition: state
      entity_id: light.bedroom
      state: 'on'

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ trigger.entity_id == 'light.bedroom' }}"
            - condition: time
              after: '11:00:00'
              before: '20:00:00'
          sequence:
            - delay:
                minutes: 10
            - service: light.turn_off
              entity_id: light.bedroom

      default:
        - service: light.turn_off
          entity_id: light.bedroom
