---
- alias: Lights On - Bedroom

  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_hue_motion
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: numeric_state
      entity_id: sensor.bedroom_hue_light_level
      below: 3
    - condition: state
      entity_id: light.bedroom
      state: 'off'
    - condition: or
      conditions:
        - condition: state
          entity_id: input_select.day_state
          state: Afternoon
        - condition: state
          entity_id: input_select.day_state
          state: Evening

  action:
    - service: light.turn_on
      entity_id: light.bedroom
