---
- alias: Lights - Bedroom - Off

  trigger:
    - platform: state
      entity_id: input_boolean.home_state
      to: 'off'

  action:
    - service: light.turn_off
      entity_id: light.bedroom
