---
- alias: Lights - Bedroom

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away

  condition:
    - condition: state
      entity_id: light.bedroom
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.bedroom
