---
- alias: 'Lights - Bedroom'
  mode: 'queued'

  trigger:
    - platform: 'state'
      entity_id: 'input_select.home_state'
      to: 'Away'

  action:
    - choose:
        - conditions:
            - condition: 'state'
              entity_id: 'light.bedroom'
              state: 'on'
          sequence:
            - service: 'light.turn_off'
              entity_id: 'light.bedroom'
