---
- alias: Lights - Bedroom - Sensor
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_hue_motion
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.bedroom_hue_light_level
      below: 5
    - condition: state
      entity_id: binary_sensor.in_bed_sensor
      state: 'off'
    - condition: time
      after: '09:00:00'
      before: '21:30:00'

  action:
    - choose:
        conditions:
          - condition: state
            entity_id: input_select.day_state
            state: Night
        sequence:
          - service: light.turn_on
            entity_id: light.bedroom

      default:
        - service: light.turn_on
          entity_id: light.bedroom
        - delay:
            minutes: 15
        - service: light.turn_off
          entity_id: light.bedroom
