---
- alias: Lights - Bedroom - On

  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_hue_motion
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: numeric_state
      entity_id: sensor.bedroom_hue_light_level
      below: 5
    - condition: state
      entity_id: light.bedroom
      state: 'off'
    - condition: time
      after: '11:00:00'
      before: '21:30:00'
  action:
    - service: light.turn_on
      entity_id: light.bedroom
