---
- alias: Speaker - Bedroom - Off

  trigger:
    - platform: state
      entity_id: input_boolean.home_state
      to: 'off'

  action:
    - service: media_player.turn_off
      entity_id: media_player.bedroom_beast
