---
dark:
  lovelace-background: "center / cover no-repeat url('/local/night.jpg') fixed"

  text-color: '#DADADB'
  text-medium-light-color: '#A0A2A8'
  text-medium-color: '#80828A'
  text-dark-color: '#6A6B74'
  accent-color: '#008bef'
  accent-medium-color: '#2686c1'
  background-color: '#3b4049'
  background-color-2: '#484E59'
  background-card-color: '#434952'
  border-color: '#383C46'

  primary-color: '#363941'
  text-primary-color: 'var(--text-color)'

  paper-listbox-background-color: 'var(--background-color)'
  sidebar-icon-color: 'var(--text-medium-color)'
  sidebar-selected-icon-color: 'var(--text-medium-light-color)'
  sidebar-selected-text-color: 'var(--text-color)'

  paper-card-header-color: 'var(--text-color)'
  primary-background-color: 'var(--background-color)'
  mdc-theme-primary: 'var(--accent-medium-color)'
  card-background-color: 'var(--background-card-color)'

  paper-card-background-color: 'var(--background-card-color)'
  dark-primary-color: 'var(--text-color)'
  primary-text-color: 'var(--text-color)'
  paper-listbox-color: 'var(--text-color)'
  light-primary-color: 'var(--text-dark-color)'
  secondary-text-color: 'var(--text-medium-color)'
  disabled-text-color: 'var(--text-dark-color)'
  paper-dialog-button-color: 'var(--text-color)'
  secondary-background-color: 'var(--background-color-2)'

  paper-item-icon-color: 'var(--text-dark-color)'
  paper-item-icon-active-color: 'var(--accent-color)'

  switch-checked-color: 'var(--accent-color)'
  switch-unchecked-button-color: 'var(--text-medium-light-color)'
  switch-unchecked-track-color: '#767682'

  paper-slider-active-color: 'var(--accent-color)'
  paper-slider-container-color: 'var(--text-dark-color)'
  paper-slider-knob-color: 'var(--text-medium-light-color)'
  paper-slider-knob-start-color: 'var(--text-medium-light-color)'

  ha-card-box-shadow: 'inset 0px 0px 0px 1px var(--border-color)'
