---
- alias: "Climate - Landing - Active"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Home"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
    - condition: "template"
      value_template: "{{ not is_state('input_select.day_state', 'Night') }}"
  action:
    - service: "climate.set_temperature"
      data:
        entity_id: "climate.landing"
        temperature: 21
    - service: "notify.telegram"
      data:
        title: "*Hass Climate Info*"
        message: "Landing heating turned on"

- alias: "Climate - Landing - Inactive"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Night"
  action:
    - service: "climate.set_temperature"
      data:
        entity_id: "climate.landing"
        temperature: 17
    - service: "notify.telegram"
      data:
        title: "*Hass Climate Info*"
        message: "Landing heating turned off"
