---
type: vertical-stack
cards:
  - title: Landing
    type: glance
    entities:
      - entity: climate.landing
      - entity: sensor.landing_temperature
      - entity: sensor.landing_humidity
    state_color: true
    show_icon: true
    show_name: false

  - type: entities
    entities:
      - entity: light.landing
      - entity: switch.workstation_plug_2
      - entity: media_player.landing_wifi
    show_header_toggle: false
