---
type: vertical-stack
cards:
  - title: Landing
    type: glance
    entities:
      - entity: media_player.landing
      - entity: climate.landing
      - entity: sensor.landing_temperature
      - entity: sensor.landing_humidity
    state_color: true
    show_icon: true
    show_name: false

  - type: entities
    entities:
      - entity: light.landing_light
      - entity: light.landing_corner
    show_header_toggle: false
