- platform: group
  name: Living Room
  entities:
    - light.back
    - light.front

- platform: group
  name: Bedroom
  entities:
    - light.stoof
    - light.gerald

- platform: group
  name: All Lights
  entities:
    - light.back
    - light.front
    - light.stoof
    - light.gerald
