- platform: group
  name: Living Room
  entities:
    - light.living_room_back
    - light.living_room_front

- platform: group
  name: Bedroom
  entities:
    - light.bedroom_stoof
    - light.bedroom_gerald

- platform: group
  name: All Lights
  entities:
    - light.living_room_back
    - light.living_room_front
    - light.bedroom_stoof
    - light.bedroom_gerald
