- platform: group
  name: All Lights
  entities:
    - light.living_room_back
    - light.living_room_front

- platform: group
  name: Living Room
  entities:
    - light.living_room_back
    - light.living_room_front
