---
- alias: "Manual Git Pull"
  trigger:
    platform: "webhook"
    webhook_id: "manual_restart"
  action:
    - service: "notify.telegram"
      data:
        title: "*Hass System Info*"
        message: "Manual restart triggered"
    - service: "homeassistant.restart"
