---
- alias: Update Available Notification
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      to: 'on'
  action:
    - service: notify.bertie_iphone
      data:
        message: "🛵 Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }} is available."
