---
- "sensor.living_room_temperature"
- "sensor.living_room_humidity"
- "sensor.landing_temperature"
- "sensor.landing_humidity"
- "sensor.bedroom_temperature"
- "sensor.bedroom_humidity"
- "sensor.spare_room_temperature"
- "sensor.spare_room_humidity"
