---
- "sensor.speedtest_download"
- "sensor.speedtest_upload"
- "sensor.archer_vr400_kib_s_sent"
- "sensor.archer_vr400_kib_s_received"
- "sensor.archer_vr400_packets_sent"
- "sensor.archer_vr400_packets_received"
- "sensor.archer_vr400_packets_s_sent"
- "sensor.archer_vr400_packets_s_received"
