- platform: travisci
    api_key: !secret github_access_token
    monitored_conditions:
      - last_build_state
- platform: darksky
  api_key: !secret dark_sky_api_key
  forecast:
    - 0
  monitored_conditions:
    - summary
    - icon
    - temperature