- alias: Heating - Bathroom - Schedule
  mode: single

  triggers:
    - trigger: state
      entity_id: sensor.heating_bathroom_automatic_target
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: climate.bathroom
      from:
        - unavailable
        - unknown
    - trigger: state
      entity_id: timer.heating_bathroom_boost
      from: active
      to: idle

  condition:
    - condition: state
      entity_id: timer.heating_bathroom_boost
      state: idle
    - condition: template
      value_template: "{{ states('sensor.heating_bathroom_automatic_target') | float(none) is not none }}"
  action:
    - action: climate.turn_on
      target:
        entity_id: climate.bathroom
    - action: climate.set_temperature
      target:
        entity_id: climate.bathroom
      data:
        temperature: "{{ states('sensor.heating_bathroom_automatic_target') | float }}"
