---
type: "vertical-stack"
cards:
  - type: "button"
    tap_action:
      action: "call-service"
      service: "automation.trigger"
    entity: "automation.climate_coming_home_boost"
    icon: "mdi:fire"
    show_name: false
    show_state: false
