---
type: vertical-stack
cards:
  - type: glance
    entities:
      - entity: person.bertie
      - entity: person.steph
      - entity: input_select.home_state
      - entity: input_select.day_state
      - entity: input_select.guests_state
    show_state: true
    show_icon: true
    show_name: false

  - type: weather-forecast
    entity: weather.dark_sky

  - !include ../areas/desktop/spare_room.yaml
  - !include ../areas/desktop/bathroom.yaml
