- alias: "Away Mode"
  trigger:
    platform: state
    entity_id: group.family
    to: "not_home"
  action:
    service: light.turn_off
    entity_id: group.all_lights
- alias: "Home Mode"
  trigger:
    platform: state
    entity_id: group.family
    to: "home"
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    service: light.turn_on
    entity_id: light.living_room
