- alias: "Away Mode"
  trigger:
    platform: state
    entity_id: group.family
    to: "not_home"
  action:
    service: light.turn_off
    entity_id: group.all_lights
- alias: "Home Mode"
  trigger:
    platform: state
    entity_id: group.family
    to: "home"
  condition:
    condition: sun
    after: sunset
    after_offset: "-02:00:00"
  action:
    service: light.turn_on
    entity_id: light.living_room
- alias: "Broadcast Person arriving"
  trigger:
    - platform: state
      entity_id: person.bertie
      to: "home"
    - platform: state
      entity_id: person.steph
      to: "home"
    - platform: state
      entity_id: person.freddie
      to: "home"
  condition:
    condition: state
    entity_id: "group.family"
    state: "home"
  action:
    service: tts.google_say
    entity_id: media_player.kitchen_speaker
    data_template:
      message: >
        {{ trigger.to_state.name }} has arrived. You'd better make them a brew!
