- alias: "Steph Chinley"
  trigger:
    platform: state
    entity_id: person.steph
    to: "Chinley Station"
  condition:
    condition: time
    after: "14:00:00"
  action:
    - service: notify.telegram
      data:
        title: "*Steph has arrived*"
        message: "at Chinley station"
    - service: tts.google_say
      entity_id: media_player.kitchen_speaker
      data:
        message: "Steph is at Chinley station"
