---
- title: "Home"
  icon: "mdi:home"
  panel: false
  path: "default_view"
  cards:
    - type: "vertical-stack"
      cards:
        - title: "Living Room"
          type: "glance"
          entities:
            - entity: "climate.living_room"
            - entity: "sensor.living_room_temperature"
            - entity: "sensor.living_room_humidity"
            - entity: "media_player.living_room_tv"
          state_color: true
          show_icon: true
          show_name: false
          columns: 4
        - type: "entities"
          entities:
            - entity: "light.front"
            - entity: "light.back"
          show_header_toggle: false

        - title: "Landing"
          type: "glance"
          entities:
            - entity: "climate.landing"
            - entity: "sensor.landing_temperature"
            - entity: "sensor.landing_humidity"
          state_color: true
          show_icon: true
          show_name: false
        - type: "entities"
          entities:
            - entity: "light.landing"
          show_header_toggle: false

    - type: "vertical-stack"
      cards:
        - type: "glance"
          entities:
            - entity: "person.bertie"
            - entity: "person.steph"
            - entity: "input_select.home_state"
            - entity: "input_select.day_state"
          show_state: true
          show_icon: true
          show_name: true
        - type: "weather-forecast"
          entity: "weather.dark_sky"

    - type: "vertical-stack"
      cards:
        - title: "Bedroom"
          type: "glance"
          entities:
            - entity: "climate.bedroom"
            - entity: "sensor.bedroom_temperature"
            - entity: "sensor.bedroom_humidity"
            - entity: "media_player.bedroom_speaker"
          state_color: true
          show_icon: true
          show_name: false
          show_state: true
          columns: 4
        - type: "entities"
          entities:
            - entity: "light.bertie"
            - entity: "light.stoof"
            - entity: "light.gerald"
          show_header_toggle: false

        - title: "Spare Room"
          type: "glance"
          entities:
            - entity: "climate.spare_room"
            - entity: "sensor.spare_room_temperature"
            - entity: "sensor.spare_room_humidity"
          show_icon: true
          show_name: false
