---
- title: "Home"
  icon: "mdi:home"
  panel: false
  path: "default_view"
  badges:
    - "person.steph"
    - "person.bertie"

  cards:
    - type: "vertical-stack"
      cards:
        - title: "Living Room"
          type: "glance"
          entities:
            - entity: "climate.living_room"
            - entity: "sensor.living_room_temperature"
            - entity: "sensor.living_room_humidity"
            - entity: "light.back"
            - entity: "light.front"
            - entity: "media_player.living_room_tv"
          show_icon: true
          show_name: false
          columns: 3
        - title: "Landing"
          type: "glance"
          entities:
            - entity: "climate.landing"
            - entity: "sensor.landing_temperature"
            - entity: "sensor.landing_humidity"
            - entity: "light.landing"
          show_icon: true
          show_name: false

    - type: "vertical-stack"
      cards:
        - type: "weather-forecast"
          entity: "weather.dark_sky"
        - type: "light"
          entity: "light.all_lights"

    - type: "vertical-stack"
      cards:
        - title: "Bedroom"
          type: "glance"
          entities:
            - entity: "climate.bedroom"
            - entity: "sensor.bedroom_temperature"
            - entity: "sensor.bedroom_humidity"
            - entity: "light.bertie"
            - entity: "light.stoof"
            - entity: "light.gerald"
          show_icon: true
          show_name: false
          show_state: true
          columns: 3
        - title: "Spare Room"
          type: "glance"
          entities:
            - entity: "climate.spare_room"
            - entity: "sensor.spare_room_temperature"
            - entity: "sensor.spare_room_humidity"
          show_icon: true
          show_name: false
