---
- title: "Home"
  icon: "mdi:home"
  panel: false
  path: "default_view"
  badges:
    - "person.steph"
    - "person.bertie"
  cards:
    - type: "vertical-stack"
      cards:
        - title: "Living Room"
          type: "glance"
          entities:
            - entity: "climate.living_room"
            - entity: "sensor.living_room_temperature"
            - entity: "sensor.living_room_humidity"
            - entity: "media_player.living_room_tv"
          state_color: true
          show_icon: true
          show_name: false
          columns: 4
        - type: "entities"
          entities:
            - entity: "light.front"
            - entity: "light.back"
          show_header_toggle: false

        - title: "Spare Room"
          type: "glance"
          entities:
            - entity: "climate.spare_room"
            - entity: "sensor.spare_room_temperature"
            - entity: "sensor.spare_room_humidity"
          state_color: true
          show_icon: true
          show_name: false

    - type: "vertical-stack"
      cards:
        - type: "weather-forecast"
          entity: "weather.dark_sky"
        - type: "vertical-stack"
          cards:
            - type: "button"
              tap_action:
                action: "toggle"
              entity: "light.living_room"
            - type: "horizontal-stack"
              cards:
                - type: "button"
                  tap_action:
                    action: "toggle"
                  entity: "light.bedroom"
                - type: "button"
                  tap_action:
                    action: "toggle"
                  entity: "light.landing"


    - type: "vertical-stack"
      cards:
        - title: "Bedroom"
          type: "glance"
          entities:
            - entity: "climate.bedroom"
            - entity: "sensor.bedroom_temperature"
            - entity: "sensor.bedroom_humidity"
          state_color: true
          show_icon: true
          show_name: false
          show_state: true
          columns: 3
        - type: "entities"
          entities:
            - entity: "light.bertie"
            - entity: "light.stoof"
            - entity: "light.gerald"
          show_header_toggle: false

        - title: "Spare Room"
          type: "glance"
          entities:
            - entity: "climate.spare_room"
            - entity: "sensor.spare_room_temperature"
            - entity: "sensor.spare_room_humidity"
          show_icon: true
          show_name: false
