---
- title: "Home"
  icon: "mdi:home"
  panel: false
  path: "default_view"
  badges:
    - "person.steph"
    - "person.bertie"
    - type: "entity-filter"
      icon: "mdi:home"
      show_name: false
      entities:
        - "input_select.home_state"
      state_filter:
        - "Home"
    - type: "entity-filter"
      icon: "mdi:home-outline"
      show_name: false
      entities:
        - "input_select.home_state"
      state_filter:
        - "Away"
  cards:
    - type: "vertical-stack"
      cards:
        - title: "Living Room"
          type: "glance"
          entities:
            - entity: "climate.living_room"
            - entity: "sensor.living_room_temperature"
            - entity: "sensor.living_room_humidity"
            - entity: "light.back"
              icon: "mdi:floor-lamp"
            - entity: "light.front"
              icon: "mdi:lamp"
            - entity: "media_player.living_room_tv"
          show_icon: true
          show_name: false
          columns: 3
        - title: "Landing"
          type: "glance"
          entities:
            - entity: "climate.landing"
            - entity: "sensor.landing_temperature"
            - entity: "sensor.landing_humidity"
            - entity: "light.landing"
              icon: "mdi:floor-lamp"
          show_icon: true
          show_name: false

    - type: "vertical-stack"
      cards:
        - type: "weather-forecast"
          entity: "weather.dark_sky"
        - type: "light"
          entity: "light.all_lights"

    - type: "vertical-stack"
      cards:
        - title: "Bedroom"
          type: "glance"
          entities:
            - entity: "climate.bedroom"
            - entity: "sensor.bedroom_temperature"
            - entity: "sensor.bedroom_humidity"
            - entity: "light.bertie"
              icon: "mdi:lightbulb-cfl"
            - entity: "light.stoof"
              icon: "mdi:lightbulb-cfl"
            - entity: "light.gerald"
              icon: "mdi:lava-lamp"
          show_icon: true
          show_name: false
          show_state: true
          columns: 3
        - title: "Spare Room"
          type: "glance"
          entities:
            - entity: "climate.spare_room"
            - entity: "sensor.spare_room_temperature"
            - entity: "sensor.spare_room_humidity"
          show_icon: true
          show_name: false
