---
- title: "System"
  icon: "mdi:chart-bar-stacked"
  cards:
    - type: "vertical-stack"
      cards:
        - type: "custom:mini-graph-card"
          hours_to_show: 24
          points_per_hour: 2
          entities:
            - "sensor.memory_use_percent"
          show:
            labels: true
          color_thresholds:
            - value: 0
              color: "#00ff00"
            - value: 20
              color: "#ffa500"
            - value: 80
              color: "#ff0000"

        - type: "custom:mini-graph-card"
          hours_to_show: 24
          points_per_hour: 2
          entities:
            - "sensor.processor_use"
          show:
            labels: true
          color_thresholds:
            - value: 0
              color: "#00ff00"
            - value: 20
              color: "#ffa500"
            - value: 80
              color: "#ff0000"
