---
title: "Home - Mobile"
icon: "mdi:home"
panel: false
path: "default_view"
cards:
  - !include "../cards/simple/header_mobile.yaml"
  - !include "../cards/simple/living_room.yaml"
  - !include "../cards/simple/landing.yaml"
  - !include "../cards/simple/bedroom.yaml"
  - !include "../cards/simple/spare_room.yaml"
