---
title: Home - Mobile
icon: mdi:home
panel: false
path: default_view
cards:
  - !include ../cards/layouts/header.mobile.yaml
  - !include ../cards/areas/mobile/living_room.yaml
  - !include ../cards/areas/mobile/landing.yaml
  - !include ../cards/areas/mobile/bedroom.yaml
  - !include ../cards/areas/mobile/spare_room.yaml
  - !include ../cards/areas/mobile/bathroom.yaml
