---
title: Home - Desktop
icon: mdi:home
panel: false
path: default_view
cards:
  - type: vertical-stack
    cards:
      - !include ../cards/areas/desktop/living_room.yaml
  - type: vertical-stack
    cards:
      - type: glance
        entities:
          - entity: person.bertie
          - entity: person.steph
          - entity: input_select.home_state
          - entity: input_select.day_state
          - entity: input_select.guests_state
        show_state: true
        show_icon: true
        show_name: false

      - type: weather-forecast
        entity: weather.dark_sky

      - !include ../cards/areas/desktop/spare_room.yaml
      - !include ../cards/areas/desktop/bathroom.yaml
      - !include ../cards/areas/desktop/kitchen.yaml

  - type: vertical-stack
    cards:
      - !include ../cards/areas/desktop/landing.yaml
      - !include ../cards/areas/desktop/bedroom.yaml
