---
- alias: "Climate - Spare Room"
  mode: "queued"

  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"

  action:
    - choose:
        - conditions:
            - condition: "state"
              entity_id: "input_select.day_state"
              state: "Morning"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
            - condition: "state"
              entity_id: "input_select.guests_state"
              state: "True"
          sequence:
            - service: "tado.set_climate_timer"
              data:
                entity_id: "climate.spare_room"
                time_period: "02:00:00"
                temperature: 21

      default:
        - service: "climate.turn_off"
          data:
            entity_id: "climate.spare_room"
