---
- alias: 'Climate - Spare Room'
  mode: 'queued'

  trigger:
    - platform: 'state'
      entity_id: 'input_select.day_state'
      to: 'Morning'
    - platform: 'state'
      entity_id: 'input_select.day_state'
      to: 'Afternoon'
    - platform: 'state'
      entity_id: 'input_select.home_state'
      to: 'Away'
    - platform: 'numeric_state'
      entity_id: 'sensor.spare_room_humidity'
      above: 75

  action:
    - choose:
        - conditions:
            - condition: 'state'
              entity_id: 'input_select.day_state'
              state: 'Morning'
            - condition: 'state'
              entity_id: 'input_select.home_state'
              state: 'Home'
          sequence:
            - service: 'tado.set_climate_timer'
              data:
                entity_id: 'climate.spare_room'
                time_period: '02:00:00'
                temperature: 19

        - conditions:
            - condition: 'state'
              entity_id: 'input_select.home_state'
              state: 'Home'
            - condition: 'state'
              entity_id: 'input_select.guests_state'
              state: 'False'
            - condition: 'numeric_state'
              entity_id: 'sensor.spare_room_humidity'
              above: 75
            - condition: 'template'
              value_template: "{{ not is_state('input_select.day_state', 'Night') }}"
          sequence:
            - service: 'tado.set_climate_timer'
              data:
                entity_id: 'climate.spare_room'
                time_period: '01:00:00'
                temperature: 23

      default:
        - service: 'climate.turn_off'
          data:
            entity_id: 'climate.spare_room'
