---
- alias: Climate - Spare Room - Morning

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.spare_room
        temperature: 21
