---
- alias: ALDI Zone Alerts
  trigger:
    - platform: state
      entity_id: person.steph
      to: ALDI
    - platform: state
      entity_id: person.steph
      from: ALDI
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: person.steph
              state: ALDI
          sequence:
            - service: notify.bertie_iphone
              data:
                message: 🥑 Stoof has arrived at ALDI
        - conditions:
            - condition: template
              value_template: "{{ states('person.steph') != 'ALDI'  }}"
          sequence:
            - service: notify.bertie_iphone
              data:
                message: 🥑 Stoof has left ALDI
