---
- alias: ALDI Zone Alerts
  trigger:
    - platform: state
      entity_id: person.steph
      from: not_home
      to: ALDI
    - platform: state
      entity_id: person.steph
      from: ALDI
      to: not_home
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: person.steph
              state: ALDI
          sequence:
            - service: notify.bertie_iphone
              data:
                message: 🥑 Stoof has arrived at ALDI
        - conditions:
            - condition: state
              entity_id: person.steph
              state: not_home
          sequence:
            - service: notify.bertie_iphone
              data:
                message: 🥑 Stoof has left ALDI
