---
- alias: Zone Alerts - Bertie
  trigger:
    - platform: state
      entity_id: person.bertie

  condition:
    - condition: template
      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'

  action:
    - choose:
        conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state != 'not_home' }}"
        sequence:
          - service: notify.bertie_iphone
            data:
              message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} left {{ trigger.from_state.state }}"

      default:
        - service: notify.bertie_iphone
          data:
            message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} arrived at {{ trigger.to_state.state }}"
