---
- alias: Car Stolen
  trigger:
    - platform: template
      value_template: >
        {{ state_attr('device_tracker.vw', 'motion') }}
      for: '00:00:20'

  action:
    - service: notify.bertie_iphone
      data:
        message: 🚙 The car is moving
