---
- alias: Zone Alerts
  trigger:
    - platform: state
      entity_id:
        - person.bertie
        - person.steph
        - person.freddie
        - person.bernie
        - person.hugh
      for:
        seconds: 45

  condition:
    - condition: template
      value_template: '{{ trigger.from_state.state != trigger.to_state.state }}'

  action:
    - choose:
        conditions:
          - condition: template
            value_template: "{{ trigger.from_state.state != 'not_home' }}"
        sequence:
          - service_template: >
              {% if trigger.entity_id == 'person.bertie' %}
                notify.stoof_iphone
              {% elif trigger.entity_id == 'person.steph' %}
                notify.bertie_iphone
              {% else %}
                notify.boof_group
              {% endif %}
            data:
              message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} left {{ trigger.from_state.state }}"

      default:
        - service_template: >
            {% if trigger.entity_id == 'person.bertie' %}
              notify.stoof_iphone
            {% elif trigger.entity_id == 'person.steph' %}
              notify.bertie_iphone
            {% else %}
              notify.boof_group
            {% endif %}
          data:
            message: "{{ state_attr(trigger.entity_id, 'friendly_name') }} arrived at {{ trigger.to_state.state }}"
