- alias: Heating - Bedroom - Schedule
  mode: single

  triggers:
    - trigger: state
      entity_id: sensor.heating_bedroom_automatic_target
    - trigger: homeassistant
      event: start
    - trigger: time_pattern
      minutes: /15

  condition:
    - condition: state
      entity_id: binary_sensor.upstairs_windows
      state: "off"
    - condition: template
      value_template: "{{ states('sensor.heating_bedroom_automatic_target') | float(none) is not none }}"
  action:
    - action: climate.turn_on
      target:
        entity_id: climate.bedroom
    - action: climate.set_temperature
      target:
        entity_id: climate.bedroom
      data:
        temperature: "{{ states('sensor.heating_bedroom_automatic_target') | float }}"
