- alias: Heating - Bedroom - Window
  mode: single

  triggers:
    - trigger: state
      entity_id: binary_sensor.upstairs_windows

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "on"
          sequence:
            - action: climate.turn_off
              target:
                entity_id: climate.bedroom
        - conditions:
            - condition: state
              entity_id: binary_sensor.upstairs_windows
              state: "off"
            - condition: template
              value_template: "{{ states('sensor.heating_bedroom_automatic_target') | float(none) is not none }}"
          sequence:
            - action: climate.turn_on
              target:
                entity_id: climate.bedroom
            - action: climate.set_temperature
              target:
                entity_id: climate.bedroom
              data:
                temperature: "{{ states('sensor.heating_bedroom_automatic_target') | float }}"
