- alias: Heating - Bedroom - Schedule
  id: automation_areas_bedroom_heating_bedroom_schedule
  mode: single

  triggers:
    - trigger: state
      entity_id: sensor.heating_bedroom_automatic_target
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: climate.bedroom
      from:
        - unavailable
        - unknown
    - trigger: state
      entity_id: timer.heating_bedroom_boost
      from: active
      to: idle

  condition:
    - condition: state
      entity_id: binary_sensor.upstairs_windows
      state: "off"
    - condition: state
      entity_id: timer.heating_bedroom_boost
      state: idle
    - condition: template
      value_template: "{{ states('sensor.heating_bedroom_automatic_target') | float(none) is not none }}"
  action:
    - action: climate.turn_on
      target:
        entity_id: climate.bedroom
    - action: climate.set_temperature
      target:
        entity_id: climate.bedroom
      data:
        temperature: "{{ states('sensor.heating_bedroom_automatic_target') | float }}"
