---
- alias: Cinema Mode
  trigger:
    - platform: state
      entity_id: input_boolean.cinema_state
      to: 'on'
    - platform: state
      entity_id: input_boolean.cinema_state
      to: 'off'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.cinema_state
              state: 'on'
          sequence:
            - service: scene.apply
              data:
                transition: 2
                entities:
                  light.front:
                    state: 'on'
                    profile: relax
                  light.back: 'off'
                  light.fairy: 'off'

      default:
        - service: scene.apply
          data:
            transition: 2
            entities:
              light.front:
                state: 'on'
                profile: reading
              light.back: 'on'
              light.fairy: 'on'
