---
- alias: Cinema Mode
  trigger:
    - platform: state
      entity_id: input_boolean.cinema_state
      to: 'on'
    - platform: state
      entity_id: input_boolean.cinema_state
      to: 'off'
  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_boolean.cinema_state
              state: 'on'
          sequence:
            - service: scene.turn_on
              entity_id: scene.cinema

      default:
        - service: light.turn_on
          entity_id: light.living_room
