---
- alias: Climate - Living Room - Morning

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning
    - platform: state
      entity_id: input_select.home_state
      to: Home

  condition:
    - condition: state
      entity_id: input_select.day_state
      state: Morning
    - condition: state
      entity_id: input_select.home_state
      state: Home

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room
        temperature: 20
