---
- alias: "Climate - Living Room"
  mode: "queued"

  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Evening"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Night"
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Home"
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "state"
      entity_id: "sensor.living_room_open_window"
      to: "True"

  action:
    - choose:
        - conditions:
            - condition: "state"
              entity_id: "input_select.day_state"
              state: "Morning"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
          sequence:
            - service: "climate.set_temperature"
              data:
                entity_id: "climate.living_room"
                temperature: 19

        - conditions:
            - condition: "state"
              entity_id: "input_select.day_state"
              state: "Afternoon"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
          sequence:
            - service: "climate.set_temperature"
              data:
                entity_id: "climate.living_room"
                temperature: 20

        - conditions:
            - condition: "state"
              entity_id: "input_select.day_state"
              state: "Evening"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
          sequence:
            - service: "climate.set_temperature"
              data:
                entity_id: "climate.living_room"
                temperature: 21

        - conditions:
            - condition: "state"
              entity_id: "sensor.living_room_open_window"
              state: "True"
          sequence:
            - service: "notify.telegram"
              data:
                title: "*Hass Window Info*"
                message: "Living room door or window open"

      default:
        - service: "climate.turn_off"
          data:
            entity_id: "climate.living_room"
