---
- alias: Climate - Living Room
  mode: queued

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning
    - platform: state
      entity_id: input_select.day_state
      to: Afternoon
    - platform: state
      entity_id: input_select.day_state
      to: Evening
    - platform: state
      entity_id: input_select.day_state
      to: Night
    - platform: state
      entity_id: input_select.home_state
      to: Home
    - platform: state
      entity_id: input_select.home_state
      to: Away

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.home_state
              state: Home
            - condition: or
              conditions:
                - condition: state
                  entity_id: input_select.day_state
                  state: Morning
                - condition: state
                  entity_id: input_select.day_state
                  state: Afternoon
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.living_room
                temperature: 20
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.home_state
              state: Home
            - condition: state
              entity_id: input_select.day_state
              state: Evening
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.living_room
                temperature: 21

      default:
        - service: climate.turn_off
          data:
            entity_id: climate.living_room
