---
- alias: "Climate - Living Room"
  mode: "queued"

  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Night"
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Home"
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"

  action:
    - choose:
        - conditions:
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Afternoon"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
          sequence:
            - service: "climate.set_temperature"
              data:
                entity_id: "climate.landing"
                temperature: 19

        - conditions:
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Evening"
            - condition: "state"
              entity_id: "input_select.home_state"
              state: "Home"
          sequence:
            - service: "climate.set_temperature"
              data:
                entity_id: "climate.landing"
                temperature: 21

      default:
        - service: "climate.turn_off"
          data:
            entity_id: "climate.landing"
