---
- alias: Climate - Living Room - Off

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Night
    - platform: state
      entity_id: input_boolean.home_state
      to: 'off'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.living_room
        temperature: 15
