---
- alias: Lights - Living Room - Motion
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.living_room_motion_sensor
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    - condition: state
      entity_id: input_boolean.cinema_state
      state: 'off'
    - condition: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      below: 10

  action:
    - service: light.turn_on
      entity_id: light.living_room
    - delay:
        minutes: 15
    - service: light.turn_off
      entity_id: light.living_room
