---
- alias: Lights - Living Room - Morning

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: numeric_state
      entity_id: sensor.living_room_light
      below: 5
    - condition: state
      entity_id: light.living_room
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.living_room
