---
- alias: Lights - Living Room - Lux

  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      below: 4
      for: '00:05:00'

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: state
      entity_id: input_boolean.cinema_state
      state: 'off'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: time
      after: '05:00:00'
      before: '20:00:00'

  action:
    - service: light.turn_on
      entity_id: light.living_room
