---
- alias: Lights - Living Room - Off

  trigger:
    - platform: state
      entity_id: input_boolean.home_state
      to: 'off'
    - platform: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      above: 12
      for: '00:10:00'
    - platform: time
      at: 00:00:00

  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.living_room
