---
- alias: Lights - Living Room - Button

  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: e415bcdfc21571b4ded37e3199d199f0
        args:
          value: true

  action:
    - choose:
        conditions:
          - condition: state
            entity_id: input_boolean.cinema_state
            state: 'on'
        sequence:
          - service: input_boolean.turn_off
            entity_id: input_boolean.cinema_state

      default:
        - service: light.toggle
          entity_id: light.living_room
