---
- alias: Lights - Living Room - Off

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away
    - platform: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      above: 10
      for: '00:10:00'
    - platform: state
      entity_id: binary_sensor.in_bed_sensor
      to: 'on'

  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.living_room
