---
- alias: Lights - Living Room - Home

  trigger:
    - platform: state
      entity_id: input_boolean.home_state
      to: 'on'

  condition:
    - condition: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      below: 3
    - condition: state
      entity_id: light.living_room
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.living_room
