---
- alias: Lights Off - Living Room
  mode: single

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away
    - platform: numeric_state
      entity_id: sensor.hue_motion_sensor_1_light_level
      above: 70
    - platform: time
      at: 00:00:00

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: light.living_room
              state: 'on'
          sequence:
            - service: light.turn_off
              entity_id: light.living_room
