---
- alias: Lights Off - Living Room

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away
    - platform: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      above: 8
      for: '00:05:00'
    - platform: time
      at: 00:00:00

  condition:
    - condition: state
      entity_id: light.living_room
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.living_room
