---
- alias: Lights - Living Room - Lux - Weekend

  trigger:
    - platform: numeric_state
      entity_id: sensor.living_room_light_sensor_light
      below: 4
      for: '00:05:00'

  condition:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: state
      entity_id: input_boolean.cinema_state
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('input_select.day_state', 'Night') }}"
    - condition: state
      entity_id: light.living_room
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.living_room
