---
- alias: Plant Health - Living Room - Maranta

  trigger:
    - platform: numeric_state
      entity_id: sensor.maranta_conductivity
      below: 110
    - platform: numeric_state
      entity_id: sensor.maranta_moisture
      below: 20

  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: sensor.maranta_conductivity
              below: 110
          sequence:
            - service: notify.boof_group
              data:
                message: 🍔 The Prayer Plant is hungry

        - conditions:
            - condition: numeric_state
              entity_id: sensor.maranta_moisture
              below: 20
          sequence:
            - service: notify.boof_group
              data:
                message: 💦 The Prayer Plant is thirsty
