---
- alias: "Sensor Battery - Living Room - Cupboard"
  trigger:
    - entity_id: "sensor.living_room_cupboard_power"
      for: "24:00:00"
      platform: "state"
      to: "unavailable"
  action:
    - service: "notify.bertie_iphone"
      data:
        message: "🔋 The living room cupboard sensor battery state is unreachable"
