---
- alias: Sensor Battery - Living Room - Cupboard
  trigger:
    - entity_id: sensor.living_room_cupboard_battery
      for: 24:00:00
      platform: state
      to: unavailable
    - entity_id: sensor.living_room_cupboard_battery
      platform: numeric_state
      below: 10
  action:
    - service: notify.bertie_iphone
      data:
        message: 🔋 The living room cupboard sensor battery is '{{ trigger.to_state.state }}'
