---
- alias: Sensor Battery - Living Room - Maranta
  trigger:
    - entity_id: sensor.maranta_battery
      for: 24:00:00
      platform: state
      to: unavailable
    - entity_id: sensor.maranta_battery
      platform: numeric_state
      below: 10
  action:
    - service: notify.bertie_iphone
      data:
        message: 🔋 The Prayer Plant sensor battery state is '{{ trigger.to_state.state }}'
