---
- alias: "Away Mode"
  trigger:
    platform: "state"
    entity_id: "group.family"
    to: "not_home"
  action:
    - service: "variable.set_variable"
      data:
        variable: "home_state"
        value: "away"
