---
- alias: "Away Mode"
  trigger:
    platform: "state"
    entity_id: "group.family"
    to: "not_home"
  action:
    - service: "input_select.select_option"
      data:
        entity_id: "input_select.home_state"
        option: "Away"
