---
- alias: "Climate - Bedroom - Active"
  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
  action:
    - service: "tado.set_climate_timer"
      data:
        entity_id: "climate.bedroom"
        time_period: "02:30:00"
        temperature: 21
    - service: "notify.telegram"
      data:
        title: "*Hass Climate Info*"
        message: "Bedroom heating turned on"

- alias: "Climate - Bedroom - Inactive"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
  action:
    - service: "climate.turn_off"
      data:
        entity_id: "climate.bedroom"
    - service: "notify.telegram"
      data:
        title: "*Hass Climate Info*"
        message: "Bedroom heating turned off"
