---
- alias: "Climate - Bedroom - Active"
  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
  action:
    - service: "tado.set_climate_timer"
      data:
        entity_id: "climate.bedroom"
        time_period: "02:00:00"
        temperature: 21

- alias: "Climate - Bedroom - Inactive"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
  action:
    - service: "climate.set_preset_mode"
      data:
        entity_id: "climate.bedroom"
        preset_mode: "away"
