---
- alias: "Evening Mode"
  trigger:
    platform: "sun"
    event: "sunset"
    offset: "-02:00:00"
  action:
    - service: "variable.set_variable"
      data:
        variable: "day_state"
        value: "evening"
