---
- alias: "Evening"
  trigger:
    platform: "sun"
    event: "sunset"
    offset: "-02:00:00"
  action:
    - service: "input_select.select_option"
      data:
        entity_id: "input_select.day_state"
        option: "Evening"
