---
- alias: "Home Mode"
  trigger:
    platform: "state"
    entity_id: "group.family"
    to: "home"
  condition:
    condition: "sun"
    after: "sunset"
    after_offset: "-02:00:00"
  action:
    service: "light.turn_on"
    entity_id: "light.living_room"
