---
- alias: "Humidity Heat Boost"
  trigger:
    platform: "event"
    event_type: "state_changed"
    event_data:
      domain: "sensor"
  condition:
    - condition: "template"
      value_template: "{{ trigger.event.data.entity_id.endswith('_humidity') }}"
    - condition: "template"
      value_template: >
        {{ states({{ trigger.event.data.entity_id }}) > 75 }}
  action:
    - service: "tado.set_climate_timer"
      data:
        entity_id: >
          {% set trigger = trigger.event.data.entity_id %}
          {{ 'climate.'+x[7:-9:] }}
        temperature: 25
        time_period: "01:00:00"
    - service: "notify.telegram"
      data:
        title: "*Hass Debug*"
        message: >
          Entity ID trigger:
          {{ trigger.event.data.entity_id }}

          Ends with humidity:
          {{ trigger.event.data.entity_id.endswith('_humidity') }}

          Humidity is above 75:
          {{ states({{ trigger.event.data.entity_id }}) > 75 }}

          Climate entity to trigger:
          {% set trigger = trigger.event.data.entity_id %}
          {{ 'climate.'+x[7:-9:] }}
