---
- alias: "Good Kitty"
  trigger:
    platform: "state"
    entity_id: "input_boolean.good_kitty"
    to: "on"
  action:
    - service: "tts.google_translate_say"
      entity_id: "media_player.kitchen_speaker"
      data:
        message: "Nala is a good kitty"
