---
- alias: "Lights On"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Home"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Evening"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
    - platform: "state"
      entity_id: "input_select.weather_state"
      to: "Overcast"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
  action:
    - service: "light.turn_on"
      entity_id: "light.landing"
    - service: "light.turn_on"
      entity_id: "light.living_room"
