---
- alias: "Lights On"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Home"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Evening"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Morning"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
    - condition: "numeric_state"
      entity_id: "sensor.hue_motion_sensor_1_light_level"
      below: 90
  action:
    - service: "light.turn_on"
      entity_id: "light.landing"
    - service: "light.turn_on"
      entity_id: "light.living_room"
