---
- alias: "Lights Off"
  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Night"
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Afternoon"
  action:
    - service: "light.turn_off"
      entity_id: "light.all_lights"
