---
- alias: "Lights Off"
  trigger:
    - platform: "state"
      entity_id: "input_select.day_state"
      to: "Night"
  action:
    - service: "light.turn_off"
      entity_id: "light.landing"
    - service: "light.turn_off"
      entity_id: "light.living_room"
