---
- alias: "Lights On"
  trigger:
    - platform: "state"
      entity_id: "variable.home_state"
      to: "home"
    - platform: "state"
      entity_id: "variable.day_state"
      to: "evening"
  condition:
    - condition: "sun"
      after: "sunset"
      after_offset: "-02:00:00"
    - condition: "sun"
      before: "sunrise"
  action:
    - service: "light.turn_on"
      entity_id: "light.all_lights"
