---
- alias: "Lights On"
  trigger:
    platform: "state"
    entity_id: "input_select.home_state"
    to: "Home"
  condition:
    condition: "sun"
    after: "sunset"
    after_offset: "-02:00:00"
  action:
    - service: "light.turn_on"
      entity_id: "light.all_lights"
