---
- alias: "Morning Mode"
  trigger:
    platform: "time"
    at: "06:10:00"
  condition:
    - condition: "state"
      entity_id: "binary_sensor.workday_sensor"
      state: "on"
    - condition: "state"
      entity_id: "variable.home_state"
      state: "home"
  action:
    - service: "variable.set_variable"
      data:
        variable: "day_state"
        value: "morning"
