---
- alias: "Morning Mode"
  trigger:
    platform: "time"
    at: "06:10:00"
  condition:
    condition: "and"
    conditions:
      - condition: "sun"
        before: "sunrise"
      - condition: "state"
        entity_id: "binary_sensor.workday_sensor"
        state: "on"
      - condition: "state"
        entity_id: "group.family"
        state: "home"
  action:
    service: "light.turn_on"
    entity_id: "light.living_room"
