---
- alias: "Morning Mode"
  trigger:
    platform: state
    entity_id: group.family
    to: "home"
  condition:
    condition: and
    - condition: sun
      before: sunrise
      before_offset: "-01:00:00"
    - condition: time
      after: '06:15:00'
    - condition: state
      entity_id: 'binary_sensor.workday_sensor'
      state: 'on'
  action:
    service: light.turn_on
    entity_id: light.living_room
