---
- alias: "Morning Mode"
  trigger:
    platform: "time"
    at: "06:10:00"
  condition:
    - condition: "sun"
      before: "sunrise"
    - condition: "state"
      entity_id: "binary_sensor.workday_sensor"
      state: "on"
  action:
    - service: "input_select.select_option"
      data:
        entity_id: "input_select.day_state"
        option: "Morning"
