---
- alias: "Night Mode"
  trigger:
    platform: "time"
    at: "22:30:00"
  action:
    - service: "input_select.select_option"
      data:
        entity_id: "input_select.day_state"
        option: "Night"
