---
- alias: "Night Mode"
  trigger:
    platform: "time"
    at: "22:00:00"
  condition:
    - condition: "state"
      entity_id: "input_select.home_state"
      state: "Home"
  action:
    - service: "input_select.select_option"
      data:
        entity_id: "input_select.day_state"
        option: "Night"
