---
- alias: "Turn on TV Mode"
  initial_state: true
  trigger:
    - platform: "event"
      event_type: "ios.action_fired"
      event_data:
        actionName: "TV Mode"
  action:
    service: scene.turn_on
    entity_id: scene.tv
