---
- alias: "Turn on TV Mode"
  initial_state: true
  trigger:
    - platform: "event"
      event_type: "ios.action_fired"
      event_data:
        actionName: "TV Mode"
  action:
    service: "light.turn_off"
    entity_id: "group.all_lights"
