---
- alias: Climate - Landing - Afternoon

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Afternoon
    - platform: state
      entity_id: input_boolean.home_state
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.day_state
      state: Afternoon
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'

  action:
    - service: climate.set_temperature
      data:
        entity_id: climate.landing
        temperature: 21
