---
- alias: Climate - Landing
  mode: queued

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning
    - platform: state
      entity_id: input_select.day_state
      to: Afternoon
    - platform: state
      entity_id: input_select.day_state
      to: Night
    - platform: state
      entity_id: input_select.home_state
      to: Home
    - platform: state
      entity_id: input_select.home_state
      to: Away

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ not is_state('input_select.day_state', 'Night') }}"
            - condition: state
              entity_id: input_select.day_state
              state: Morning
            - condition: state
              entity_id: input_select.home_state
              state: Home
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.landing
                temperature: 20

        - conditions:
            - condition: template
              value_template: "{{ not is_state('input_select.day_state', 'Night') }}"
            - condition: state
              entity_id: input_select.day_state
              state: Afternoon
            - condition: state
              entity_id: input_select.home_state
              state: Home
          sequence:
            - service: climate.set_temperature
              data:
                entity_id: climate.landing
                temperature: 21

      default:
        - service: climate.turn_off
          data:
            entity_id: climate.landing
