---
- alias: Lights - Landing - Button

  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 7e9c40fded1a2a84ca0cb6888ab2bd91
        args:
          value: true

  action:
    - choose:
        conditions:
          - condition: state
            entity_id: light.landing
            state: 'off'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.landing
    - choose:
        conditions:
          - condition: state
            entity_id: light.landing
            state: 'on'
        sequence:
          - service: light.turn_off
            data:
              entity_id: light.landing
