---
- alias: Lights On - Landing
  mode: single

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Home
    - platform: state
      entity_id: input_select.day_state
      to: Morning
    - platform: sun
      event: sunset
      offset: '-00:45:00'

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: input_select.home_state
              state: Home
            - condition: template
              value_template: "{{ state_attr('sun.sun','elevation') | int < 3.5 }}"
            - condition: state
              entity_id: light.landing
              state: 'off'
          sequence:
            - service: light.turn_on
              entity_id: light.landing
