---
- alias: Lights - Landing - Motion
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.landing_motion_sensor
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    # - condition: state
    #   entity_id: input_select.day_state
    #   state: Night

  action:
    - service: light.turn_on
      entity_id: light.landing
    - delay:
        minutes: 3
    - service: light.turn_off
      entity_id: light.landing
