---
- alias: Lights - Landing - Button

  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 7e9c40fded1a2a84ca0cb6888ab2bd91
        args:
          value: 'true'

  action:
    - choose:
        conditions:
          - condition: state
            entity_id: light.landing_corner
            state: 'off'
        sequence:
          - service: light.turn_on
            data:
              entity_id: light.landing_corner
              brightness: 255

      default:
        - service: light.turn_off
          entity_id: light.landing_corner
