---
- alias: Lights - Landing - Button

  trigger:
    - platform: event
      event_type: zha_event
      data:
        device_id: 7e9c40fded1a2a84ca0cb6888ab2bd91
        args:
          value: true

  action:
    - service: notify.bertie_iphone
      data:
        message: WOOOOWW
