---
- alias: Lights - Landing - Sunset - On

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: template
      value_template: "{{ state_attr('sun.sun','elevation') | int < 5 }}"
    - condition: state
      entity_id: light.landing
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.landing
