---
- alias: Lights - Landing - Motion
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.landing_hue_motion
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    - condition: numeric_state
      entity_id: sensor.landing_hue_light_level
      below: 5
    - condition: time
      before: '09:00:00'
      after: '18:00:00'
    - condition: state
      entity_id: binary_sensor.roberts_macbook_pro_active
      state: 'off'

  action:
    - service: light.turn_on
      data:
        entity_id: light.landing
        brightness: 255
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.landing
