---
- alias: "Lights Off - Landing"
  mode: "queued"

  trigger:
    - platform: "state"
      entity_id: "input_select.home_state"
      to: "Away"
    - platform: "time"
      at: "00:00:00"

  action:
    - choose:
        - conditions:
            - condition: "state"
              entity_id: "light.landing"
              state: "on"
          sequence:
            - service: "light.turn_off"
              entity_id: "light.landing"
