---
- alias: Lights - Landing - Weekend - On

  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    - condition: state
      entity_id: light.landing
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'off'

  action:
    - service: light.turn_on
      entity_id: light.landing
