---
- alias: Lights - Landing - Motion
  mode: restart

  trigger:
    - platform: state
      entity_id: binary_sensor.landing_motion_sensor
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'
    - condition: template
      value_template: "{{ state_attr('sun.sun','elevation') | int < 5 }}"
    - condition: time
      after: '17:30:00'
      before: '08:00:00'

  action:
    - service: light.turn_on
      entity_id: light.landing
    - delay:
        minutes: 5
    - service: light.turn_off
      entity_id: light.landing
