---
- alias: Lights - Landing - Weekday - On

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Evening

  condition:
    - condition: state
      entity_id: input_select.home_state
      state: Home
    - condition: state
      entity_id: light.landing
      state: 'off'
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: 'on'

  action:
    - service: light.turn_on
      entity_id: light.landing
