---
- alias: Lights - Landing - Off

  trigger:
    - platform: state
      entity_id: input_select.home_state
      to: Away
    - platform: time
      at: '00:00:00'
    - platform: sun
      event: sunrise
      offset: '+00:30:00'

  condition:
    - condition: state
      entity_id: light.landing
      state: 'on'

  action:
    - service: light.turn_off
      entity_id: light.landing
