---
- alias: Sensor Low Battery
  trigger:
    - platform: numeric_state
      below: 10
      entity_id:
        - sensor.maranta_battery
        - sensor.christmas_tree_battery
        - sensor.living_room_cupboard_battery
        - sensor.living_room_light_sensor_battery
        - sensor.living_room_button_power
        - sensor.landing_button_power
        - sensor.living_room_motion_sensor_power
        - sensor.landing_motion_sensor_power
    - platform: state
      to: unavailable
      for: 06:00:00
      entity_id:
        - sensor.maranta_battery
        - sensor.christmas_tree_battery
        - sensor.living_room_cupboard_battery
        - sensor.living_room_light_sensor_battery
        - sensor.living_room_button_power
        - sensor.landing_button_power
        - sensor.living_room_motion_sensor_power
        - sensor.landing_motion_sensor_power

  action:
    - service: notify.bertie_iphone
      data:
        message: 🔋 The {{ state_attr(trigger.entity_id, 'friendly_name') }} level is {{ trigger.to_state.state }}
