---
- alias: Sensor Low Battery
  trigger:
    - platform: numeric_state
      below: 10
      entity_id:
        - sensor.maranta_battery
        - sensor.living_room_cupboard_battery
        - sensor.living_room_light_sensor_battery
    - platform: numeric_state
      below: 3
      entity_id:
        - sensor.maranta_battery
        - sensor.living_room_cupboard_battery
        - sensor.living_room_light_sensor_battery

  action:
    - service: notify.bertie_iphone
      data:
        message: 🔋 The {{ state_attr(trigger.entity_id, 'friendly_name') }} level is at {{ trigger.to_state.state }}
