- alias: Heating - Attic - Schedule
  id: automation_areas_attic_heating_attic_schedule
  mode: restart

  triggers:
    - trigger: state
      entity_id: sensor.heating_attic_automatic_target
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: climate.attic
      from:
        - unavailable
        - unknown
    - trigger: state
      entity_id: timer.heating_attic_boost
      from: active
      to: idle

  condition:
    - condition: state
      entity_id: timer.heating_attic_boost
      state: idle
    - condition: template
      value_template: "{{ states('sensor.heating_attic_automatic_target') | float(none) is not none }}"
  action:
    - action: climate.turn_on
      target:
        entity_id: climate.attic
    - action: climate.set_temperature
      target:
        entity_id: climate.attic
      data:
        temperature: "{{ states('sensor.heating_attic_automatic_target') | float }}"
