---
- alias: Climate - Bathroom - Morning

  trigger:
    - platform: state
      entity_id: input_select.day_state
      to: Morning

  condition:
    - condition: state
      entity_id: input_boolean.home_state
      state: 'on'

  action:
    - service: tado.set_climate_timer
      data:
        entity_id: climate.bathroom
        time_period: 02:00:00
        temperature: 23
