- alias: Heating - Downstairs - Schedule
  id: automation_areas_downstairs_heating_downstairs_schedule
  mode: single

  triggers:
    - trigger: state
      entity_id: sensor.heating_downstairs_automatic_target
    - trigger: homeassistant
      event: start
    - trigger: state
      entity_id: climate.downstairs
      from:
        - unavailable
        - unknown
    - trigger: state
      entity_id: timer.heating_downstairs_boost
      from: active
      to: idle

  condition:
    - condition: state
      entity_id: binary_sensor.living_room_window_opening
      state: "off"
    - condition: state
      entity_id: timer.heating_downstairs_boost
      state: idle
    - condition: template
      value_template: "{{ states('sensor.heating_downstairs_automatic_target') | float(none) is not none }}"
  action:
    - action: climate.turn_on
      target:
        entity_id: climate.downstairs
    - action: climate.set_temperature
      target:
        entity_id: climate.downstairs
      data:
        temperature: "{{ states('sensor.heating_downstairs_automatic_target') | float }}"
