- alias: Heating - Downstairs - Window
  id: automation_areas_downstairs_heating_downstairs_window
  mode: single

  triggers:
    - trigger: state
      entity_id: binary_sensor.living_room_window_opening
    - trigger: homeassistant
      event: start

  action:
    - choose:
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "on"
          sequence:
            - action: timer.cancel
              target:
                entity_id: timer.heating_downstairs_boost
            - action: climate.turn_off
              target:
                entity_id: climate.downstairs
        - conditions:
            - condition: state
              entity_id: binary_sensor.living_room_window_opening
              state: "off"
            - condition: template
              value_template: "{{ states('sensor.heating_downstairs_automatic_target') | float(none) is not none }}"
          sequence:
            - action: climate.turn_on
              target:
                entity_id: climate.downstairs
            - action: climate.set_temperature
              target:
                entity_id: climate.downstairs
              data:
                temperature: "{{ states('sensor.heating_downstairs_automatic_target') | float }}"
