name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy stubbed secrets
      run: mv travis/mock_secrets.yaml secrets.yaml
    - name: Print HA version
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: python -m homeassistant --version
    - name: Check HA config
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: sudo mkdir /ssl; sudo touch /ssl/fullchain.pem; sudo touch /ssl/privkey.pem; python -m homeassistant --script check_config --config ./ --info all
