name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy stub secrets
      run: mv travis/mock_secrets.yaml secrets.yaml
    - name: Home Assistant Configuration Check
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: python -m homeassistant --version

