name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy stub secrets
      run: mv travis/mock_secrets.yaml secrets.yaml
    - name: Stub SSH keys
      run:  |
        sudo mkdir /ssl
        sudo touch /ssl/fullchain.pem
        sudo touch /ssl/privkey.pem
    - name: Check HA configuration
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: python -m homeassistant --version

