name: CI

on: [push]

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Copy stub secrets
      run: mv travis/mock_secrets.yaml secrets.yaml
    - name: Stub SSH keys
      run:  |
        mkdir ./ssl
        touch ./ssl/fullchain.pem
        touch ./ssl/privkey.pem
    - name: Print HA version
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: python -m homeassistant --version
    - name: Check HA configg
      uses: "docker://homeassistant/home-assistant:latest"
      with:
        args: python -m homeassistant --script check_config --config ./ --info all
