---
name: "Test"

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - "config-refactor"

jobs:
  deploy:
    name: "Deploy Config via Git Pull Addon"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Getting configuration from GitHub"
        uses: "actions/checkout@v1"
      - name: "Install SSH key"
        uses: "shimataro/ssh-key-action@v2"
        with:
          key: "${{ secrets.SSH_KEY }}"
          name: "hass_deploy"
          known_hosts: "${{ secrets.KNOWN_HOSTS }}"
      - name: "rsync over ssh"
        run: |
          touch test.txt
          rsync test.txt ${{ secrets.RSYNC_URL }}:/config/
